### Register new user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "João da Silva",
    "CPF": "12345678913",
    "email": "joao5@gmail.com",
    "password": "12345"
}