### Register new user
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "João da Silva",
    "CPF": "12345678914",
    "email": "joao6@gmail.com",
    "password": "123456"
}

### Authenticate user
POST http://localhost:8080/auth/sessions
Content-Type: application/json

{
    "login": "joao@gmail.com",
    "password": "123456"
}

